---
title: "main"
author: "Pons Léa"
date: "`r Sys.Date()`"
---

### Library
library(readxl)
library(dplyr)
library(stringr)
library(openxlsx)
library(tidyr)
library(ggplot2)

### Set directory 
DATA_PATH = file.path("data")
SOUR_PATH = file.path("sources")
NOTE_PATH = file.path("notebooks")
RESULTS_PATH = file.path("results")

### Open the file 
PATH = file.path(DATA_PATH, "data_1st_imp.xlsx")
data = read_xlsx(PATH)

### Remove the participants who did not pass the attention check 
data <- data %>%
  filter(AC03_01 == 101)
  
#################### Step 1 - organize questionnaire data ######################
### Result file 
n_videos = 10
result_1st_imp = data.frame(matrix(ncol = 0, nrow = nrow(data) * n_videos))

# Descriptive
result_1st_imp$CASE = rep(data$CASE, each = n_videos)
result_1st_imp$Age = rep(data$DE03x01, each = n_videos)
result_1st_imp$Gender = rep(ifelse(data$DE08 == 1, "F", "H"), each = n_videos)
result_1st_imp$Pro_Sante = rep(data$DE12, each = n_videos)

# Video
vid_cols = grep("VI03_", colnames(data)) 
result_1st_imp$vid = as.vector(t(data[, vid_cols]))

# Num
result_1st_imp$num_video = rep(1:n_videos, times = nrow(data))

# Type 
result_1st_imp$Type = ifelse(
  grepl("Video_P", result_1st_imp$vid),
  "Healthy",
  "Patient"
)

# 1st imp 
im_columns = list(
  Sympathique = c("IM01_01", "IM07_01", "IM13_01", "IM19_01", "IM25_01", "IM31_01", "IM37_01", "IM43_01", "IM49_01", "IM55_01"),
  Bizarre = c("IM02_01", "IM08_01", "IM14_01", "IM20_01", "IM26_01", "IM32_01", "IM38_01", "IM44_01", "IM50_01", "IM56_01"),
  Intelligente = c("IM03_01", "IM09_01", "IM15_01", "IM21_01", "IM27_01", "IM33_01", "IM39_01", "IM45_01", "IM51_01", "IM57_01"),
  Appreciable = c("IM04_01", "IM10_01", "IM16_01", "IM22_01", "IM28_01", "IM34_01", "IM40_01", "IM46_01", "IM52_01", "IM58_01"),
  Confiance = c("IM05_01", "IM11_01", "IM17_01", "IM23_01", "IM29_01", "IM35_01", "IM41_01", "IM47_01", "IM53_01", "IM59_01"),
  Dominante = c("IM06_01", "IM12_01", "IM18_01", "IM24_01", "IM30_01", "IM36_01", "IM42_01", "IM48_01", "IM54_01", "IM60_01")
)

for (col in names(im_columns)) {
  result_1st_imp[[col]] <- as.vector(t(data[, im_columns[[col]]]))
}

rm(im_columns)

# Behavioral intention 
bi_columns = list(
  Conversation = c("BI01_01", "BI05_01", "BI09_01", "BI13_01", "BI17_01", "BI21_01", "BI25_01", "BI29_01", "BI33_01", "BI37_01"),
  Temps = c("BI02_01", "BI06_01", "BI10_01", "BI14_01", "BI18_01", "BI22_01", "BI26_01", "BI30_01", "BI34_01", "BI38_01"),
  Voisin = c("BI03_01", "BI07_01", "BI11_01", "BI15_01", "BI19_01", "BI23_01", "BI27_01", "BI31_01", "BI35_01", "BI39_01"),
  Assis = c("BI04_01", "BI08_01", "BI12_01", "BI16_01", "BI20_01", "BI24_01", "BI28_01", "BI32_01", "BI36_01", "BI40_01")
)

for (col in names(bi_columns)) {
  result_1st_imp[[col]] = as.vector(t(data[, bi_columns[[col]]]))
}

rm(bi_columns)

### By items
impressions_long = result_1st_imp %>%
  pivot_longer(
    cols = c(Sympathique, Bizarre, Intelligente, Appreciable, Confiance, Dominante, Conversation, Temps, Voisin, Assis), 
    names_to = "Impression",
    values_to = "Score"
  ) %>%
  mutate(Impression = case_when(
    Impression == "Sympathique" ~ "Attractive",
    Impression == "Bizarre" ~ "Awkward",
    Impression == "Intelligente" ~ "Intelligent",
    Impression == "Appreciable" ~ "Likeable",
    Impression == "Confiance" ~ "Confident",
    Impression == "Dominante" ~ "Dominant",
    Impression == "Conversation" ~ "Conversation",
    Impression == "Temps" ~ "Time",
    Impression == "Voisin" ~ "Live nearby",
    Impression == "Assis" ~ "Seated",
    TRUE ~ Impression
  ))

ggplot(impressions_long, aes(x = Impression, y = Score, fill = Type)) +
  stat_summary(fun = mean, geom = "bar", position = "dodge") + 
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(0.9), width = 0.2) +
  theme_minimal() +
  labs(title = "First Impressions",
       x = "First Impression",
       y = "Mean Score") +
  scale_fill_manual(
    values = c("Patient" = "steelblue", "Healthy" = "orange"), 
    labels = c("Patient" = "ISZ - no label", "Healthy" = "HC - no label")
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

